//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONG_NO
    {
        [Display(Name = "Mã công nợ")]
        public string MaCN { get; set; }

        [Display(Name = "Mã đại lý")]
        public string MaDL { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        public virtual DAI_LY DAI_LY { get; set; }
    }
}
