//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HANG_HOA
    {
        [Display(Name = "Mã hàng hóa")]
        public string MaHH { get; set; }

        [Display(Name = "Tên hàng hóa")]
        public string TenHangHoa { get; set; }

        [Display(Name = "Đơn vị tính")]
        public string DonViTinh { get; set; }

        [Display(Name = "Đơn giá")]
        public int DonGia { get; set; }

        [Display(Name = "Mã loại")]
        public string MaLoai { get; set; }

        [Display(Name = "Mã nhà cung cấp")]
        public string MaNCC { get; set; }

        [Display(Name = "Tồn kho kế hoạch")]
        public int TonKhoDuKien { get; set; }

        [Display(Name = "Định mức tồn kho")]
        public int DinhMucTK { get; set; }

        [Display(Name = "Mã loại")]
        public virtual LOAI_HANG_HOA LOAI_HANG_HOA { get; set; }

        [Display(Name = "Mã nhà cung cấp")]
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
