//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHI_TIET_PCK
    {
        [Display(Name = "Mã phiếu chuyển kho")]
        public string MaPCK { get; set; }

        public int STT { get; set; }

        [Display(Name = "Mã hàng hóa")]
        public string MaHH { get; set; }

        [Display(Name = "Số lượng")]
        public int SoLuong { get; set; }

        [Display(Name = "Ghi chú")]
        public string Ghichu { get; set; }
    
        public virtual PHIEU_CHUYEN_KHO PHIEU_CHUYEN_KHO { get; set; }
        public virtual HANG_HOA HANG_HOA { get; set; }
    }
}
