//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DON_DAT_HANG
    {
        [Display(Name = "Mã đơn đặt hàng")]
        public string MaDDH { get; set; }

        [Display(Name = "Ngày đặt")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public System.DateTime NgayDat { get; set; }

        [Display(Name = "Địa chỉ nhận hàng")]
        public string DiaChi { get; set; }

        [Display(Name = "Giao hàng")]
        public bool GiaoHang { get; set; }

        [Display(Name = "Mã nhân viên")]
        public string MaNV { get; set; }

        [Display(Name = "Mã đại lý")]
        public string MaDL { get; set; }
    
        public virtual DAI_LY DAI_LY { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
