//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAI_HANG_HOA
    {
        [Display(Name = "Mã loại")]
        public string MaLoai { get; set; }

        [Display(Name = "Tên loại")]
        public string TenLoai { get; set; }
    }
}
