//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HTTTEntities : DbContext
    {
        public HTTTEntities()
            : base("name=HTTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KHO_HANG> KHO_HANG { get; set; }
        public virtual DbSet<LOAI_HANG_HOA> LOAI_HANG_HOA { get; set; }
        public virtual DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<Ton_kho> Ton_kho { get; set; }
        public virtual DbSet<CongNo> CongNoes { get; set; }
        public virtual DbSet<DAI_LY> DAI_LY { get; set; }
        public virtual DbSet<DON_DAT_HANG> DON_DAT_HANG { get; set; }
        public virtual DbSet<CHI_TIET_DDH> CHI_TIET_DDH { get; set; }
        public virtual DbSet<CHI_TIET_PNH> CHI_TIET_PNH { get; set; }
        public virtual DbSet<PHIEU_CHUYEN_KHO> PHIEU_CHUYEN_KHO { get; set; }
        public virtual DbSet<CHI_TIET_PCK> CHI_TIET_PCK { get; set; }
        public virtual DbSet<PHIEU_NHAP_HANG> PHIEU_NHAP_HANG { get; set; }
        public virtual DbSet<HANG_HOA> HANG_HOA { get; set; }
    }
}
