//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHIEU_NHAP_HANG
    {
        [Display(Name = "Mã phiếu nhập")]
        public string MaPNH { get; set; }

        [Display(Name = "Ngày nhập")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public System.DateTime NgayNhap { get; set; }

        [Display(Name = "Nhận hàng")]
        public bool NhanHang { get; set; }

        [Display(Name = "Mã nhà cung cấp")]
        public string MaNCC { get; set; }

        [Display(Name = "Mã nhân viên")]
        public string MaNV { get; set; }

        [Display(Name = "Gửi")]
        public bool Gui { get; set; }
    
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
