//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.HTTT2.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ton_kho
    {
        [Display(Name = "Mã hàng hóa")]
        public string MaHH { get; set; }

        [Display(Name = "Mã kho hàng")]
        public string MaKH { get; set; }

        [Display(Name = "Số lượng")]
        public int SoLuong { get; set; }
    
        public virtual KHO_HANG KHO_HANG { get; set; }
        public virtual HANG_HOA HANG_HOA { get; set; }
    }
}
